In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("chat.txt",header=None,on_bad_lines="skip",encoding='utf8')

In [4]:
df

,0,1,2
0,Messages and calls are end-to-end encrypted. N...,not even WhatsApp,can read or listen to them.
1,[6/17/26,4:52:40 PM] Nalini Lkg I Class Teacher: Class...,2026
2,Namaste parents,NaN,NaN
3,Gentle reminder to the Bhagavad Gita competit...,NaN,NaN
4,Interested parents are requested to enroll the...,NaN,NaN
...,...,...,...
75,[9/3/26,7:51:25 PM] Nalini Lkg I Class Teacher: Namas...,NaN
76,Today's assembly photo,NaN,NaN
77,[9/3/26,7:52:05 PM] You: Thankyou so much mam🙏🏻😊,NaN
78,[9/3/26,8:53:57 PM] Nalini Lkg I Class Teacher: <imag...,NaN
79,[9/3/26,9:05:30 PM] You: Thankyou mam 🙏🏻,NaN

In [12]:
df

Index([0, 1, 2], dtype='int64')

In [7]:
df=df.drop(0)

In [8]:
match = re.search(r'(\[.*?\])', text)

if match:
    bracket_part = match.group(1)
    rest_part = text[:match.start()] + text[match.end():]

print("Bracket:", bracket_part)
print("Rest:", rest_part)

,0,1,2
1,[6/17/26,4:52:40 PM] Nalini Lkg I Class Teacher: Class...,2026
2,Namaste parents,NaN,NaN
3,Gentle reminder to the Bhagavad Gita competit...,NaN,NaN
4,Interested parents are requested to enroll the...,NaN,NaN
5,We encourage our young learners to take part i...,NaN,NaN
...,...,...,...
75,[9/3/26,7:51:25 PM] Nalini Lkg I Class Teacher: Namas...,NaN
76,Today's assembly photo,NaN,NaN
77,[9/3/26,7:52:05 PM] You: Thankyou so much mam🙏🏻😊,NaN
78,[9/3/26,8:53:57 PM] Nalini Lkg I Class Teacher: <imag...,NaN
79,[9/3/26,9:05:30 PM] You: Thankyou mam 🙏🏻,NaN

In [22]:
df[[2]].value_counts()

2
2026                                                                                                                                                                              3
and stay connected with the Vedritam story.                                                                                                                                       1
the same will be intimated to you in advance.                                                                                                                                     1
this is Meenaal Magesh's mother. This is to inform you that Meenaal is unwell and will be on leave to school today.                                                               1
couldn't find Meenaal's EMIS number using our Mobile numbers.  Any idea whether it has been registered already in government site or we can keep that field blank in Bio data?    1
we are available on September 3rd. Meenaal will be leave on sep 7.                                                                                                                1
Meenaal will be on leave today as well.                                                                                                                                           1
Name: count, dtype: int64

In [25]:
df.columns=['Date','Time','Chat']

In [26]:
df

,Date,Time,Chat
1,[6/17/26,4:52:40 PM] Nalini Lkg I Class Teacher: Class...,2026
2,Namaste parents,NaN,NaN
3,Gentle reminder to the Bhagavad Gita competit...,NaN,NaN
4,Interested parents are requested to enroll the...,NaN,NaN
5,We encourage our young learners to take part i...,NaN,NaN
...,...,...,...
75,[9/3/26,7:51:25 PM] Nalini Lkg I Class Teacher: Namas...,NaN
76,Today's assembly photo,NaN,NaN
77,[9/3/26,7:52:05 PM] You: Thankyou so much mam🙏🏻😊,NaN
78,[9/3/26,8:53:57 PM] Nalini Lkg I Class Teacher: <imag...,NaN
79,[9/3/26,9:05:30 PM] You: Thankyou mam 🙏🏻,NaN

In [27]:
Message=df["Date"].str.split("[",n=1,expand=True)

In [33]:
Message

                                                    0        1
1                                                      6/17/26
2                                     Namaste parents      NaN
3   Gentle reminder to  the Bhagavad Gita competit...      NaN
4   Interested parents are requested to enroll the...      NaN
5   We encourage our young learners to take part i...      NaN
..                                                ...      ...
75                                                      9/3/26
76                             Today's assembly photo      NaN
77                                                      9/3/26
78                                                      9/3/26
79                                                      9/3/26

[79 rows x 2 columns]

In [34]:
Message[0].isnull().value_counts()

0
False    79
Name: count, dtype: int64

In [35]:
df['Date']=Message[1]

In [36]:
df

       Date                                               Time   Chat
1   6/17/26   4:52:40 PM] Nalini Lkg I Class Teacher: Class...   2026
2       NaN                                                NaN    NaN
3       NaN                                                NaN    NaN
4       NaN                                                NaN    NaN
5       NaN                                                NaN    NaN
..      ...                                                ...    ...
75   9/3/26   7:51:25 PM] Nalini Lkg I Class Teacher: Namas...    NaN
76      NaN                                                NaN    NaN
77   9/3/26           7:52:05 PM] You: Thankyou so much mam🙏🏻😊    NaN
78   9/3/26   8:53:57 PM] Nalini Lkg I Class Teacher: <imag...    NaN
79   9/3/26                   9:05:30 PM] You: Thankyou mam 🙏🏻    NaN

[79 rows x 3 columns]

In [44]:
NewTime=df["Time"].str.split("]",n=1,expand=True)
NewTime

              0                                                 1
1    4:52:40 PM   Nalini Lkg I Class Teacher: Class LKG/17th June
2           NaN                                               NaN
3           NaN                                               NaN
4           NaN                                               NaN
5           NaN                                               NaN
..          ...                                               ...
75   7:51:25 PM        Nalini Lkg I Class Teacher: Namaste ma'am
76          NaN                                               NaN
77   7:52:05 PM                      You: Thankyou so much mam🙏🏻😊
78   8:53:57 PM       Nalini Lkg I Class Teacher: <image omitted>
79   9:05:30 PM                              You: Thankyou mam 🙏🏻

[79 rows x 2 columns]

In [45]:
NewTime1=NewTime[1].str.split(":",n=1,expand=True)
NewTime1

                              0                         1
1    Nalini Lkg I Class Teacher       Class LKG/17th June
2                           NaN                       NaN
3                           NaN                       NaN
4                           NaN                       NaN
5                           NaN                       NaN
..                          ...                       ...
75   Nalini Lkg I Class Teacher            Namaste ma'am
76                          NaN                       NaN
77                          You   Thankyou so much mam🙏🏻😊
78   Nalini Lkg I Class Teacher           <image omitted>
79                          You           Thankyou mam 🙏🏻

[79 rows x 2 columns]

In [46]:
df['Time']=NewTime[0]
df['Name']=NewTime1[0]
df

       Date         Time   Chat                         Name
1   6/17/26   4:52:40 PM   2026   Nalini Lkg I Class Teacher
2       NaN          NaN    NaN                          NaN
3       NaN          NaN    NaN                          NaN
4       NaN          NaN    NaN                          NaN
5       NaN          NaN    NaN                          NaN
..      ...          ...    ...                          ...
75   9/3/26   7:51:25 PM    NaN   Nalini Lkg I Class Teacher
76      NaN          NaN    NaN                          NaN
77   9/3/26   7:52:05 PM    NaN                          You
78   9/3/26   8:53:57 PM    NaN   Nalini Lkg I Class Teacher
79   9/3/26   9:05:30 PM    NaN                          You

[79 rows x 4 columns]

In [62]:
#df["Message"]=    Message[0] + ' ' + NewTime1[1] + ' ' + df['Chat']

df["Message"] = (
    Message[0].fillna('') + ' ' +
    NewTime1[1].fillna('') + ' ' +
    df['Chat'].fillna('')
)

Message
False    79
Name: count, dtype: int64

In [63]:
df["Message"]

1                             Class LKG/17th June  2026
2                                     Namaste parents
3     Gentle reminder to  the Bhagavad Gita competit...
4     Interested parents are requested to enroll the...
5     We encourage our young learners to take part i...
                            ...
75                                      Namaste ma'am
76                             Today's assembly photo
77                             Thankyou so much mam🙏🏻😊
78                                     <image omitted>
79                                     Thankyou mam 🙏🏻
Name: Message, Length: 79, dtype: str

In [76]:
df=df.drop('Chat',axis=1)

In [80]:
df

,Date,Time,Name,Message
1,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,Class LKG/17th June 2026
2,6/17/26,NaN,NaN,Namaste parents
3,6/17/26,NaN,NaN,Gentle reminder to the Bhagavad Gita competit...
4,6/17/26,NaN,NaN,Interested parents are requested to enroll the...
5,6/17/26,NaN,NaN,We encourage our young learners to take part i...
...,...,...,...,...
75,9/3/26,7:51:25 PM,Nalini Lkg I Class Teacher,Namaste ma'am
76,9/3/26,NaN,NaN,Today's assembly photo
77,9/3/26,7:52:05 PM,You,Thankyou so much mam🙏🏻😊
78,9/3/26,8:53:57 PM,Nalini Lkg I Class Teacher,<image omitted>
79,9/3/26,9:05:30 PM,You,Thankyou mam 🙏🏻

In [78]:
df['Date']=df['Date'].ffill()

In [81]:
df['Time']=df['Time'].ffill()

In [83]:
df['Name']=df['Name'].ffill()

In [84]:
df

,Date,Time,Name,Message
1,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,Class LKG/17th June 2026
2,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,Namaste parents
3,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,Gentle reminder to the Bhagavad Gita competit...
4,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,Interested parents are requested to enroll the...
5,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,We encourage our young learners to take part i...
...,...,...,...,...
75,9/3/26,7:51:25 PM,Nalini Lkg I Class Teacher,Namaste ma'am
76,9/3/26,7:51:25 PM,Nalini Lkg I Class Teacher,Today's assembly photo
77,9/3/26,7:52:05 PM,You,Thankyou so much mam🙏🏻😊
78,9/3/26,8:53:57 PM,Nalini Lkg I Class Teacher,<image omitted>
79,9/3/26,9:05:30 PM,You,Thankyou mam 🙏🏻

In [126]:
#df.to_csv("Filrt_chat_data.csv")

In [86]:
df.isnull().value_counts()

Date   Time   Name   Message
False  False  False  False      79
Name: count, dtype: int64

In [88]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 79 entries, 1 to 79
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     79 non-null     str
 1   Time     79 non-null     str
 2   Name     79 non-null     str
 3   Message  79 non-null     str
dtypes: str(4)
memory usage: 2.6 KB

In [91]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
dataset=df

In [92]:
dataset.dropna(inplace=True)

In [99]:
sid=SentimentIntensityAnalyzer()
senti=sid.polarity_scores(df['Message'][4])
senti

{'neg': 0.0, 'neu': 0.876, 'pos': 0.124, 'compound': 0.4019}

In [103]:
def sentimentalAnalysis(data,columnname):

    #downloading vader_Lexicon for the process
    import matplotlib.pyplot as plt
    import seaborn as sns
    from nltk.sentiment.vader import SentimentIntensityAnalyzer
    
    sid=SentimentIntensityAnalyzer()
    data.dropna(inplace=True)
    
    #senti=sid.polarity_scores(df['Message'][4])
    data['Scores']=data[columnname].apply(lambda commenttext: sid.polarity_scores(commenttext))
    data['Compound']=data['Scores'].apply(lambda score_dict: score_dict['compound'])
    data['Negative']=data['Scores'].apply(lambda score_dict: score_dict['neg'])
    data['Positive']=data['Scores'].apply(lambda score_dict: score_dict['pos'])
    data['Neutral']=data['Scores'].apply(lambda score_dict: score_dict['neu'])

    data['comp_score']= data['Compound'].apply(lambda c: 'pos' if c >=0 else 'neg')
    plt.clf()

    posneg=pd.DataFrame(data['comp_score'].value_counts())
    return posneg,data

In [104]:
pos,data_senti=sentimentalAnalysis(dataset,columnname='Message')

In [105]:
data_senti

,Date,Time,Name,Message,Scores,Compound,Negative,Positive,Neutral,comp_score
1,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,Class LKG/17th June 2026,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos
2,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,Namaste parents,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos
3,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,Gentle reminder to the Bhagavad Gita competit...,"{'neg': 0.0, 'neu': 0.884, 'pos': 0.116, 'comp...",0.4404,0.0,0.116,0.884,pos
4,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,Interested parents are requested to enroll the...,"{'neg': 0.0, 'neu': 0.876, 'pos': 0.124, 'comp...",0.4019,0.0,0.124,0.876,pos
5,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,We encourage our young learners to take part i...,"{'neg': 0.0, 'neu': 0.621, 'pos': 0.379, 'comp...",0.7269,0.0,0.379,0.621,pos
...,...,...,...,...,...,...,...,...,...,...
75,9/3/26,7:51:25 PM,Nalini Lkg I Class Teacher,Namaste ma'am,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos
76,9/3/26,7:51:25 PM,Nalini Lkg I Class Teacher,Today's assembly photo,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos
77,9/3/26,7:52:05 PM,You,Thankyou so much mam🙏🏻😊,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos
78,9/3/26,8:53:57 PM,Nalini Lkg I Class Teacher,<image omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos
79,9/3/26,9:05:30 PM,You,Thankyou mam 🙏🏻,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos

In [106]:
pos

            count
comp_score
pos            74
neg             5

In [108]:
#data_senti['comp_score'].iloc[0]

'pos'

In [ ]:
######TOPIC MODELLING#####

In [111]:
from sklearn.feature_extraction.text import CountVectorizer

In [110]:
###vectorizer = HashingVectorizer(n_features=16, alternate_sign=False, stop_words='english') -- cannot use it for topic modelling

In [112]:
vectorizer = CountVectorizer(stop_words='english') 
#  Transform the text into a clean Document-Term Matrix (DTM)
# This keeps track of actual word strings instead of destroying them like a hash.
dtm = vectorizer.fit_transform(df['Message'])

In [113]:
from sklearn.decomposition import LatentDirichletAllocation
# Initialize and fit Topic Model
lda = LatentDirichletAllocation(n_components=5, random_state=42)
lda.fit(dtm)

LatentDirichletAllocation(n_components=5, random_state=42)

In [117]:
# Extract the explicit vocabulary names mapped to each feature index
# Note: This step completely breaks if you use HashingVectorizer instead!
feature_names = vectorizer.get_feature_names_out()
feature_names

array(['05', '06', '12', '17th', '19th', '2026', '20th', '22', '25',
       '25th', '26th', '27', '27th', '3rd', '72', 'accurate', 'activity',
       'advance', 'ahead', 'annual', 'appreciate', 'assembly', 'audio',
       'auditions', 'available', 'best', 'bhagavad', 'bhakti', 'bi',
       'bio', 'blank', 'book', 'card', 'chapter', 'check', 'class',
       'classes', 'classroom', 'code', 'collaborative', 'competition',
       'completed', 'connected', 'cooperation', 'correct', 'couldn',
       'data', 'date', 'dav', 'dear', 'delay', 'details', 'emis',
       'encourage', 'enriching', 'enroll', 'ensure', 'fail', 'field',
       'form', 'forward', 'forwarded', 'friday', 'fu9nsyemiqpvluaxpgrx',
       'gentle', 'gita', 'government', 'group', 'happy', 'having', 'head',
       'headmistress', 'held', 'hi', 'ho', 'holiday', 'holidays', 'home',
       'https', 'id', 'idea', 'image', 'inform', 'initiating',
       'interested', 'intimated', 'invite', 'issuance', 'joining', 'july',
       'june', 'kg', 'kindly', 'late', 'learners', 'leave', 'link', 'lkg',
       'look', 'lot', 'ma', 'magesh', 'mam', 'means', 'meenaal',
       'messages', 'mobile', 'monday', 'month', 'mother', 'namaste',
       'need', 'news', 'note', 'noted', 'number', 'numbers', 'nursery',
       'office', 'omitted', 'opportunity', 'orientation', 'pallikaranai',
       'parent', 'parents', 'partnership', 'photo', 'pkn', 'pre', 'prekg',
       'principal', 'printing', 'process', 'processing', 'program', 'qr',
       'read', 'reference', 'regards', 'registered', 'regular',
       'regularly', 'reminder', 'requested', 'requesting', 'return',
       'rhymes', 'right', 'roundup', 'sangraha', 'saturday', 'scan',
       'school', 'sent', 'sep', 'september', 'session', 'share', 'site',
       'stay', 'story', 'submission', 'submissions', 'submit', 'taking',
       'teacher', 'temperature', 'thank', 'thanks', 'thankyou', 'time',
       'timely', 'today', 'tomorrow', 'ukg', 'unwell', 'using',
       'vedritam', 'vice', 'ward', 'xii', 'year', 'yoga', 'young',
       'zfrmz'], dtype=object)

In [122]:
for index,topic in enumerate(lda.components_):
    results=([feature_names[i] for i in topic.argsort()[-10:]])
    print(results)

['prekg', 'classes', 'xii', 'lkg', 'dav', 'school', 'dear', 'june', '2026', 'parents']
['government', 'bio', 'blank', 'hi', '22', '06', 'mam', 'thanks', 'regards', 'namaste']
['rhymes', 'reference', 'thank', '26th', 'note', 'friday', 'vedritam', 'ensure', 'group', 'kindly']
['2026', 'june', 'lkg', 'inform', 'ward', 'mam', 'noted', 'regards', 'teacher', 'class']
['school', '2026', 'thankyou', 'image', 'omitted', 'today', 'leave', 'hi', 'meenaal', 'mam']

In [123]:
topic_results=lda.transform(dtm)
df['Topic']=topic_results.argmax(axis=1)

In [124]:
df['Topic'].value_counts()

Topic
3    24
4    20
0    15
1    13
2     7
Name: count, dtype: int64

In [125]:
df

,Date,Time,Name,Message,Scores,Compound,Negative,Positive,Neutral,comp_score,Topic
1,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,Class LKG/17th June 2026,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos,3
2,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,Namaste parents,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos,1
3,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,Gentle reminder to the Bhagavad Gita competit...,"{'neg': 0.0, 'neu': 0.884, 'pos': 0.116, 'comp...",0.4404,0.0,0.116,0.884,pos,0
4,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,Interested parents are requested to enroll the...,"{'neg': 0.0, 'neu': 0.876, 'pos': 0.124, 'comp...",0.4019,0.0,0.124,0.876,pos,0
5,6/17/26,4:52:40 PM,Nalini Lkg I Class Teacher,We encourage our young learners to take part i...,"{'neg': 0.0, 'neu': 0.621, 'pos': 0.379, 'comp...",0.7269,0.0,0.379,0.621,pos,1
...,...,...,...,...,...,...,...,...,...,...,...
75,9/3/26,7:51:25 PM,Nalini Lkg I Class Teacher,Namaste ma'am,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos,1
76,9/3/26,7:51:25 PM,Nalini Lkg I Class Teacher,Today's assembly photo,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos,4
77,9/3/26,7:52:05 PM,You,Thankyou so much mam🙏🏻😊,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos,4
78,9/3/26,8:53:57 PM,Nalini Lkg I Class Teacher,<image omitted>,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos,4
79,9/3/26,9:05:30 PM,You,Thankyou mam 🙏🏻,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.0,0.000,1.000,pos,4

In [94]:
#import nltk
#nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/Max/nltk_data...

True

In [90]:
###!pip install nltk

Collecting nltk
  Downloading nltk-3.10.3-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: defusedxml in /Users/Max/opt/anaconda3/envs/DLenv1/lib/python3.12/site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in /Users/Max/opt/anaconda3/envs/DLenv1/lib/python3.12/site-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in /Users/Max/opt/anaconda3/envs/DLenv1/lib/python3.12/site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.9.10-cp312-cp312-macosx_10_13_x86_64.whl.metadata (40 kB)
Requirement already satisfied: tqdm in /Users/Max/opt/anaconda3/envs/DLenv1/lib/python3.12/site-packages (from nltk) (4.70.0)
Downloading nltk-3.10.3-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 3.7 MB/s  0:00:00 eta 0:00:01
Downloading regex-2026.9.10-cp312-cp312-macosx_10_13_x86_64.whl (297 kB)
Installing collected packages: regex, nltk
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [nltk][32m1/2 [nltk]
Successfully installed nltk-3.10.3 regex-2026.9.10